import re

KEYWORDS = {
    # Palabras clave
    r'\bfuncion\b': 'def',
    r'\bclase\b': 'class',
    r'\bretornar\b': 'return',
    r'\bsi\b': 'if',
    r'\bsino_si\b': 'elif',
    r'\bsino\b': 'else',
    r'\bpara\b': 'for',
    r'\bmientras\b': 'while',
    r'\bromper\b': 'break',
    r'\bcontinuar\b': 'continue',
    r'\bpasar\b': 'pass',
    r'\bimportar\b': 'import',
    r'\bdesde\b': 'from',
    r'\bcomo\b': 'as',
    r'\bintentar\b': 'try',
    r'\bexcepto\b': 'except',
    r'\bexcepto\*\b': 'except*',
    r'\bfinalmente\b': 'finally',
    r'\blanzar\b': 'raise',
    r'\bcon\b': 'with',
    r'\blambda\b': 'lambda',
    r'\bproducir\b': 'yield',
    r'\bglobal\b': 'global',
    r'\bno_local\b': 'nonlocal',
    r'\bafirmar\b': 'assert',
    r'\beliminar\b': 'del',
    r'\bno\b': 'not',
    r'\by\b': 'and',
    r'\bo\b': 'or',
    r'\bno en\b': 'not in',
    r'\bes no\b': 'is not',
    r'\ben\b': 'in',
    r'\bes\b': 'is',
    r'\bVerdadero\b': 'True',
    r'\bverdadero\b': 'True',
    r'\bFalso\b': 'False',
    r'\bfalso\b': 'False',
    r'\bNulo\b': 'None',
    r'\bnulo\b': 'None',
    # Tipos y funciones built-in
    r'\bentero\b': 'int',
    r'\bflotante\b': 'float',
    r'\bcadena\b': 'str',
    r'\bbooleano\b': 'bool',
    r'\blista\b': 'list',
    r'\bdiccionario\b': 'dict',
    r'\bconjunto\b': 'set',
    r'\btupla\b': 'tuple',
    r'\brango\b': 'range',
    r'\blongitud\b': 'len',
    r'\bmapa\b': 'map',
    r'\bfiltrar\b': 'filter',
    r'\babrir\b': 'open',
    r'\bentrada\b': 'input',
    r'\bimprimir\b': 'print',
    # Funciones trigonométricas
    r'\bseno\b': 'sin',
    r'\bcoseno\b': 'cos',
    r'\btangente\b': 'tan',
    # Anotaciones de tipo
    r'\bLista\b': 'List',
    r'\bDiccionario\b': 'Dict',
    r'\bConjunto\b': 'Set',
    r'\bTupla\b': 'Tuple',
    r'\bOpcional\b': 'Optional',
    # Excepciones y errores
    r'\bexcepcion\b': 'Exception',
    r'\bValorError\b': 'ValueError',
    r'\bTipoError\b': 'TypeError',
    r'\bIndiceError\b': 'IndexError',
    r'\bClaveError\b': 'KeyError',
    r'\bAtributoError\b': 'AttributeError',
    r'\bImportarError\b': 'ImportError',
    r'\bNombreError\b': 'NameError',
    r'\bZeroDivisionError\b': 'ZeroDivisionError',
    r'\bIOError\b': 'IOError',
    r'\bStopIteration\b': 'StopIteration',
    r'\bStopAsyncIteration\b': 'StopAsyncIteration',
    r'\bOverflowError\b': 'OverflowError',
    r'\bMemoryError\b': 'MemoryError',
    r'\bArithmeticError\b': 'ArithmeticError',
    r'\bBufferError\b': 'BufferError',
    r'\bLookupError\b': 'LookupError',
    r'\bAssertionError\b': 'AssertionError',
    r'\bEnvironmentError\b': 'EnvironmentError',
    r'\bFloatingPointError\b': 'FloatingPointError',
    r'\bGeneratorExit\b': 'GeneratorExit',
    r'\bKeyboardInterrupt\b': 'KeyboardInterrupt',
    r'\bNotImplementedError\b': 'NotImplementedError',
    r'\bOSError\b': 'OSError',
    r'\bReferenceError\b': 'ReferenceError',
    r'\bRuntimeError\b': 'RuntimeError',
    r'\bSyntaxError\b': 'SyntaxError',
    r'\bSystemError\b': 'SystemError',
    r'\bSystemExit\b': 'SystemExit',
    r'\bTabError\b': 'TabError',
    r'\bTimeoutError\b': 'TimeoutError',
    r'\bUnicodeError\b': 'UnicodeError',
    r'\bValueError\b': 'ValueError',
    r'\bZeroDivisionError\b': 'ZeroDivisionError',
    # async/await, match/case
    r'\basíncrono\b': 'async',
    r'\besperar\b': 'await',
    r'\bcoincidir\b': 'match',
    r'\bcaso\b': 'case',
    # Decoradores
    r'@metodo_estatico': '@staticmethod',
    r'@metodo_clase': '@classmethod',
    r'@propiedad': '@property',
    # Módulos estándar comunes y adicionales
    r'\bmatematicas\b': 'math',
    r'\bsistema\b': 'sys',
    r'\baleatorio\b': 'random',
    r'\bfecha\b': 'datetime',
    r'\btiempo\b': 'time',
    r'\bjson\b': 'json',
    r'\bexpresiones\b': 're',
    r'\barchivos\b': 'os',
    r'\bargumentos\b': 'argparse',
    r'\bsubprocesos\b': 'subprocess',
    r'\burl\b': 'urllib',
    r'\bpeticiones\b': 'requests',
    r'\bhttp\b': 'http',
    r'\bsqlite\b': 'sqlite3',
    r'\bcorreo\b': 'email',
    r'\bxml\b': 'xml',
    r'\bhtml\b': 'html',
    r'\btipos\b': 'typing',
    r'\blogging\b': 'logging',
    r'\bconcurrente\b': 'concurrent',
    r'\bthreading\b': 'threading',
    r'\basyncio\b': 'asyncio',
    # Variables y métodos mágicos
    r'\byo\b': 'self',
    r'\bsuper\b': 'super',
    r'\bvariable\b': '',
    r'__nombre__': '__name__',
    r'__principal__': '__main__',
    r'__inicializar__': '__init__',
    r'__texto__': '__str__',
    r'__representar__': '__repr__',
    r'__llamar__': '__call__',
    r'__obteneritem__': '__getitem__',
    r'__asignaritem__': '__setitem__',
    r'__eliminaritem__': '__delitem__',
    r'__longitud__': '__len__',
    r'__iterar__': '__iter__',
    r'__siguiente__': '__next__',
    r'__entrar__': '__enter__',
    r'__salir__': '__exit__',
    r'__contiene__': '__contains__',
    r'__igual__': '__eq__',
    r'__noigual__': '__ne__',
    r'__menor__': '__lt__',
    r'__menorigual__': '__le__',
    r'__mayor__': '__gt__',
    r'__mayorigual__': '__ge__',
}

def transpilar(codigo_espanol):
    codigo = codigo_espanol
    for esp, py in KEYWORDS.items():
        codigo = re.sub(esp, py, codigo)
    return codigo
