name: Publicar en PyPI

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Construir paquete
        run: python -m build
      - name: Publicar en PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }} 